Create simple-crud.md
tryber/mongodb-aggregation-cheatsheet pull request #4
Opened 2022-08-04 01:16 UTC by nato-re

2022-08-04 17:30 UTC, thayscosta3 requested changes

2022-08-04 17:30 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +## `SELECT`
```suggestion
## `SELECT`

**Template**

```

2022-08-04 17:30 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +SELECT campo1, campo2 FROM banco.tabela;
```suggestion
SELECT * FROM <nome-do-banco>.<nome-da-tabela>;
SELECT <campo1>, <campo2> FROM <nome-do-banco>.<nome-da-tabela>;
```

2022-08-04 17:30 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +
```suggestion

**Exemplo**

```

2022-08-04 17:30 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +SELECT campo1, campo2 FROM banco.tabela;
No course, muitas vezes usamos essa sintaxe para demonstrar templates. Você acha que faz sentido adotar aqui?

2022-08-04 17:30 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +## `SELECT`
O que você acha de destacar o que é demonstração do template do que é exemplo?

2022-08-04 17:30 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +
```suggestion
```

2022-08-04 17:30 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +SELECT * FROM banco.table
```suggestion
SELECT * FROM banco.tabela 
```

2022-08-04 17:30 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +SELECT * FROM banco.table
Os outros templates estão nesse formato.

2022-08-04 18:02 UTC, mjgargani approved these changes

2022-08-05 10:50 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +### `DISTINCT`
```suggestion
### `DISTINCT`

**Template**

```

2022-08-05 11:25 UTC, thayscosta3 approved these changes

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +### `DISTINCT`
```suggestion
### `DISTINCT`

**Template**

```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +
```suggestion

**Template**

```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +
```suggestion

**Template**

```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +**Exemplos**
```suggestion
**Exemplos**

```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +**Exemplo**
```suggestion

**Exemplo**
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +```sql
```suggestion

```sql
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +**Exemplos**
```suggestion

**Exemplos**
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +```sql
```suggestion

```sql
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +```sql
```suggestion

```sql
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +```sql
```suggestion

```sql
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +**Exemplos**
```suggestion

**Exemplos**
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +```sql
```suggestion

```sql
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +⚠️ Caso seja necessário fazer um `UPDATE` sem `WHERE`
```suggestion

⚠️ Caso seja necessário fazer um `UPDATE` sem `WHERE`:

```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +⚠️ Caso seja necessário fazer um `DELETE` sem `WHERE`
```suggestion

⚠️ Caso seja necessário fazer um `DELETE` sem `WHERE`:

```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +```sql
```suggestion

```sql
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +**Exemplo**
```suggestion

**Exemplo**
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +```sql
```suggestion

```sql
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +### `LIMIT` e `OFFSET`
```suggestion

### `LIMIT` e `OFFSET`
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +**Exemplo**
```suggestion

**Exemplo**
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +---
```suggestion
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +
```suggestion

**Template**

```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +**Exemplos**
```suggestion

**Exemplos**
```

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +**Exemplos**
Cê não acha que valeria colocar o template aqui pra padronizar?

2022-08-05 11:25 UTC, thayscosta3 commented on backend/mysql/simple-crud.md
> +**Exemplos**
```suggestion

**Exemplos**
```

2022-08-05 13:30 UTC, merged